### ISSUE TITLE
Linker failure on OSX High Sierra

### ISSUE THREAD

**Issue by Areustle** [fermi-lat/st_stream#1]
When compiling on high-sierra I encountered this linker error:

`Undefined symbols for architecture x86_64:
  "std::__1::basic_ios<char, std::__1::char_traits<char> >::fill() const", referenced from:
      st_stream::OStream::fill() const in libst_stream.a(Stream.cxx.o)
  "std::__1::basic_ios<char, std::__1::char_traits<char> >::fill(char)", referenced from:
      st_stream::OStream::fill(char) in libst_stream.a(Stream.cxx.o)
ld: symbol(s) not found for architecture x86_64`

I have rewritten the function definitions for both overloads of "fill" in the Stream class to correct the error.

**Comment by Areustle** [comment]
Created branch issue#1 to address.

**Comment by jasercion** [comment]
@Areustle committed a fix and it has now been merged to master.  Closing.
